---

vagrant_box: geerlingguy/debian9

# Composer project settings.
drupal_build_composer_project: true
drupal_build_composer: true
drupal_composer_dependencies: []

drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"

# Drupal install settings.
drupal_site_name: "HSBXL Dashboard"
drupal_core_path: "/var/www/drupalvm/web"
drupal_install_site: true

# Other overrides.
php_version: "7.1"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  - solr
  # - tideways
  - upload-progress
  - varnish
  - xdebug
  # - xhprof

drupalvm_cron_jobs:
  - name: "Drupal Cron"
    minute: "*/1"
    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron --quiet"

# Other secure defaults.
dashboard_install_dir: ''
apache_packages_state: installed

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

# Set Apache to listen on port 81 (internal only), and Varnish on 80.
apache_listen_port: "81"
varnish_listen_port: "80"
varnish_default_backend_port: "81"

drupal_enable_modules:
  - admin_toolbar
  - admin_toolbar_tools
  - auto_entitylabel
  - features_ui
  - hsbxl_gate
  - hsbxl_meeting
  - hsbxl_payments
  - pathauto
  - redirect
  - shield
  - simplified_bookkeeping

php_xdebug_default_enable: 1
php_xdebug_idekey: PHPSTORM
